import UIKit
import Foundation

//declares variables for the singleplayer game mode to store the titles, artists, albums and album covers of the genre the user chooses
var selectedGenreTitles: [String] = []
var selectedGenreArtists: [String] = []
var selectedGenreAlbums: [String] = []
var selectedGenreAlbumCovers: [UIImage] = []

//declares variables for the multiplayer game mode to store the titles, artists, albums and album covers of the genre the user chooses
var mSelectedGenreTitles: [String] = []
var mSelectedGenreArtists: [String] = []
var mSelectedGenreAlbums: [String] = []
var mSelectedGenreAlbumCovers: [UIImage] = []

//declares a variable that stores all of the titles of the rap songs within the app
var rapSongTitles: [String] = ["Mask Off", "beibs in the trap", "Deja Vu", "Fine China", "Thotiana", "Stir Fry", "Bad and Boujee", "Bank Account", "Sunflower", "Controlla", "Hotline Bling", "God's Plan", "Look Alive", "Jumpman", "Forgot About Dre", "Old Town Road", "Rockstar", "Still Dre", "ZEZE", "Loyalty", "Up", "Faith", "Champion", "Some Way", "Xo Tour Llif3", "Without Me", "You Know How We Do It", "The Real Slim Shady", "Throw Sum Mo", "Wet Dreamz", "Slippery", "Unforgettable", "SAD", "No Type", "No Role Modelz", "If I Can't", "Come and See Me", "Exchange", "Black Beatles", "21 Questions", "CC", "Motorsport", "Walk It Talk It", "In My Feelings", "No Favors", "King's Dead", "Codeine Dreaming", "Started From The Bottom", "Portland", "Gyalchester", "One Dance"]

//declares a variable that stores all of the artists of the rap songs within the app
var rapSongArtists: [String] = ["Future", "NAV", "J. Cole", "Juice WRLD", "Blueface", "Migos", "Migos", "21 Savage", "Swae Lee", "Drake", "Drake", "Drake", "Drake", "Drake", "Eminem", "Lil Nas X", "Post Malone", "Dr. Dre", "Travis Scott", "Kendrick Lamar", "NAV", "NAV", "Travis Scott", "The Weeknd", "Lil Uzi Vert", "Eminem", "Ice Cube", "Eminem", "Rae Sremmurd", "J. Cole", "Migos", "Swae Lee", "XXXTENTACION", "Rae Sremmurd", "J. Cole", "50 Cent", "PARTYNEXTDOOR", "Bryson Tiller", "Rae Sremmurd", "50 Cent", "Migos", "Migos", "Migos", "Drake", "Big Sean", "Kendrick Lamar", "Kodak Black", "Drake", "Drake", "Drake", "Drake"]

//declares a variable that stores all of the albums of the rap songs within the app
var rapSongAlbums: [String] = ["FUTURE", "Birds In The Trap Sing McKnight", "4 Your Eyez Only", "Wrld on Drugs", "Famous Cryp", "Culture II", "Culture", "Issa Album", "Spider-Man Into the Spider-Verse", "Views", "Views", "Scorpion", "Look Alive", "What A Time To Be Alive", "2001", "Old Town Road", "Beerbongs and Bentleys", "2001", "Dying to Live", "DAMN", "NAV", "Reckless", "Reckless", "NAV", "Luv is Rage 2", "The Eminem Show", "Lethal Injection", "The Marshal Mathers LP", "SremmLife", "2014 Forest Hills Drive", "Culture", "Jungle Rules", "?", "SremmLife", "2014 Forest Hills Drive", "Get Rich or Die Tryin", "PARTYNEXTDOOR3", "TRAPSOUL", "SremmLife 2", "Get Rich or Die Tryin", "Culture II", "Culture II", "Culture II", "Scorpion", "I Decided", "Black Panther", "Project Baby 2", "Nothing Was The Same", "More Life", "More Life", "Views"]

//declares a variable that stores all of the album covers of the rap songs within the app
var rapSongAlbumCovers: [UIImage] = [#imageLiteral(resourceName: "FUTURE.jpg"),#imageLiteral(resourceName: "Birds In The Trap Sing McKnight.jpg"),#imageLiteral(resourceName: "4 Your Eyez Only.jpg"),#imageLiteral(resourceName: "WRLD On Drugs.jpg"),#imageLiteral(resourceName: "Famous Cryp.jpg"),#imageLiteral(resourceName: "Culture II.jpg"),#imageLiteral(resourceName: "Culture.jpg"),#imageLiteral(resourceName: "Issa Album.jpg"),#imageLiteral(resourceName: "Spider-Verse.jpg"),#imageLiteral(resourceName: "Views.jpg"),#imageLiteral(resourceName: "Views.jpg"),#imageLiteral(resourceName: "Scorpion.jpg"),#imageLiteral(resourceName: "Look Alive.jpg"),#imageLiteral(resourceName: "What A Time To Be Alive.jpg"),#imageLiteral(resourceName: "2001.jpg"),#imageLiteral(resourceName: "Old Town Road.jpg"),#imageLiteral(resourceName: "Beerbongs and Bentleys.jpg"),#imageLiteral(resourceName: "2001.jpg"),#imageLiteral(resourceName: "Dying to Live.jpg"),#imageLiteral(resourceName: "DAMN.jpg"),#imageLiteral(resourceName: "NAV.jpg"),#imageLiteral(resourceName: "Reckless.jpg"),#imageLiteral(resourceName: "Reckless.jpg"),#imageLiteral(resourceName: "NAV.jpg"),#imageLiteral(resourceName: "Luv is Rage 2.jpg"),#imageLiteral(resourceName: "The Eminem Show.jpg"),#imageLiteral(resourceName: "Lethal Injection.jpg"),#imageLiteral(resourceName: "The Marshall Mathers LP.jpg"),#imageLiteral(resourceName: "SremmLife.jpg"),#imageLiteral(resourceName: "2014 Forest Hills Drive.jpg"),#imageLiteral(resourceName: "Culture.jpg"),#imageLiteral(resourceName: "Jungle Rules.jpg"),#imageLiteral(resourceName: "?.jpg"),#imageLiteral(resourceName: "SremmLife.jpg"),#imageLiteral(resourceName: "2014 Forest Hills Drive.jpg"),#imageLiteral(resourceName: "Get Rich or Die Tryin.jpg"),#imageLiteral(resourceName: "PARTYNEXTDOOR3.jpg"),#imageLiteral(resourceName: "TRAPSOUL.jpg"),#imageLiteral(resourceName: "SremmLife 2.jpg"),#imageLiteral(resourceName: "Get Rich or Die Tryin.jpg"),#imageLiteral(resourceName: "Culture II.jpg"),#imageLiteral(resourceName: "Culture II.jpg"),#imageLiteral(resourceName: "Culture II.jpg"),#imageLiteral(resourceName: "Scorpion.jpg"),#imageLiteral(resourceName: "I Decided.jpg"),#imageLiteral(resourceName: "Black Panther.jpg"),#imageLiteral(resourceName: "Project Baby 2.jpg"),#imageLiteral(resourceName: "Nothing Was The Same.jpg"),#imageLiteral(resourceName: "More Life.jpg"),#imageLiteral(resourceName: "More Life.jpg"),#imageLiteral(resourceName: "Views.jpg")]

//declares a variable that stores all of the titles of the pop songs within the app
var popSongTitles: [String] = ["Closer", "Paris", "It Ain't Me", "Something Just Like This", "ME!", "Delicate", "In The Name of Love", "Don't Let Me Down", "thank u, next", "Dangerous Woman", "Side To Side", "Into You", "Everyday", "Havana", "Wolves", "Wild Thoughts", "Needed Me", "Work", "Flashing Lights", "Treat You Better", "Shape of You", "Attention", "There's Nothing Holding Me Back", "Cheap Thrills", "This Is What You Came For", "Starboy", "That's What I Like", "I'm the One", "Can't Stop The Feeling", "Despacito", "I Feel It Coming", "Thunder", "Heathens", "Ride", "I Took A Pill In Ibiza", "Can't Feel My Face", "Feel It Still", "Earned It", "Shake It Off", "Blank Space", "24K Magic", "Silence", "Young, Dumb and Broke", "All We Know", "Believer", "Hands to Myself", "Same Old Love", "Sorry", "What Do You Mean", "Love Yourself", "No Brainer", "We Don't Talk Anymore", "7 rings", "Break Up With Your Girlfriend I'm Bored", "No Tears Left To Cry", "Break Free", "One Last Time"]

//declares a variable that stores all of the artists of the pop songs within the app
var popSongArtists: [String] = ["The Chainsmokers", "The Chainsmokers", "Selena Gomez", "The Chainsmokers", "Taylor Swift", "Taylor Swift", "Bebe Rexha", "Daya", "Ariana Grande", "Ariana Grande", "Ariana Grande", "Ariana Grande", "Ariana Grande", "Camila Cabello", "Selena Gomez", "Rihanna", "Rihanna", "Rihanna", "Kanye West", "Shawn Mendes", "Ed Sheeran", "Charlie Puth", "Shawn Mendes", "Sia", "Rihanna", "The Weeknd", "Bruno Mars", "Justin Bieber", "Justin Timberlake", "Justin Bieber", "The Weeknd", "Imagine Dragons", "Twenty One Pilots", "Twenty One Pilots", "Mike Posner", "The Weeknd", "Portugal The Man", "The Weeknd", "Taylor Swift", "Taylor Swift", "Bruno Mars", "Khalid", "Khalid", "The Chainsmokers", "Imagine Dragons", "Selena Gomez", "Selena Gomez", "Justin Bieber", "Justin Bieber", "Justin Bieber", "Justin Bieber", "Charlie Puth", "Ariana Grande", "Ariana Grande", "Ariana Grande", "Ariana Grande", "Ariana Grande"]

//declares a variable that stores all of the albums of the pop songs within the app
var popSongAlbums: [String] = ["Collage EP", "Paris", "It Ain't Me", "Something Just Like This", "ME!", "reputation", "In The Name of Love", "Collage EP", "thank u, next", "Dangerous Woman", "Dangerous Woman", "Dangerous Woman", "Dangerous Woman", "Camila", "Wolves", "Grateful", "Anti", "Anti", "Graduation", "Illuminate", "divide", "Voicenotes", "Illuminate", "This Is Acting", "This Is What You Came For", "Starboy", "24K Magic", "Grateful", "Trolls", "Despacito", "Starboy", "Evolve", "Suicide Squad", "Blurryface", "At Night, Alone", "Beauty Behind The Madness", "Woodstock", "Fifty Shades of Grey", "1989", "1989", "24K Magic", "Silence", "American Teen", "Collage EP", "Evolve", "Revival", "Revival", "Purpose", "Purpose", "Purpose", "Father of Asahd", "Nine Track Mind", "thank u, next", "thank u, next", "Sweetener", "My Everything", "My Everything"]

//declares a variable that stores all of the album covers of the pop songs within the app
var popSongAlbumCovers: [UIImage] = [#imageLiteral(resourceName: "Collage EP.jpg"),#imageLiteral(resourceName: "Paris.jpg"),#imageLiteral(resourceName: "It Ain't Me.jpg"),#imageLiteral(resourceName: "Something Just Like This.jpg"),#imageLiteral(resourceName: "ME!.jpg"),#imageLiteral(resourceName: "reputation.jpg"),#imageLiteral(resourceName: "In The Name of Love.jpg"),#imageLiteral(resourceName: "Collage EP.jpg"),#imageLiteral(resourceName: "thank u, next.jpg"),#imageLiteral(resourceName: "Dangerous Woman.jpg"),#imageLiteral(resourceName: "Dangerous Woman.jpg"),#imageLiteral(resourceName: "Dangerous Woman.jpg"),#imageLiteral(resourceName: "Dangerous Woman.jpg"),#imageLiteral(resourceName: "Camila.jpg"),#imageLiteral(resourceName: "Wolves.jpg"),#imageLiteral(resourceName: "Grateful.jpg"),#imageLiteral(resourceName: "Anti.jpg"),#imageLiteral(resourceName: "Anti.jpg"),#imageLiteral(resourceName: "Graduation.jpg"),#imageLiteral(resourceName: "Illuminate.jpg"),#imageLiteral(resourceName: "divide.jpg"),#imageLiteral(resourceName: "Voicenotes.jpg"),#imageLiteral(resourceName: "Illuminate.jpg"),#imageLiteral(resourceName: "This is Acting.jpg"),#imageLiteral(resourceName: "This Is What You Came For.jpg"),#imageLiteral(resourceName: "Starboy.jpg"),#imageLiteral(resourceName: "24K Magic.jpg"),#imageLiteral(resourceName: "Grateful.jpg"),#imageLiteral(resourceName: "Trolls.jpg"),#imageLiteral(resourceName: "Despacito.jpg"),#imageLiteral(resourceName: "Starboy.jpg"),#imageLiteral(resourceName: "Evolve.jpg"),#imageLiteral(resourceName: "Suicide Squad.jpg"),#imageLiteral(resourceName: "Blurryface.jpg"),#imageLiteral(resourceName: "At Night, Alone.jpg"),#imageLiteral(resourceName: "Beauty Behind The Madness.jpg"),#imageLiteral(resourceName: "Woodstock.jpg"),#imageLiteral(resourceName: "Earned It.jpg"),#imageLiteral(resourceName: "1989.jpg"),#imageLiteral(resourceName: "1989.jpg"),#imageLiteral(resourceName: "24K Magic.jpg"),#imageLiteral(resourceName: "Silence.jpg"),#imageLiteral(resourceName: "American Teen.jpg"),#imageLiteral(resourceName: "Collage EP.jpg"),#imageLiteral(resourceName: "Evolve.jpg"),#imageLiteral(resourceName: "Revival.jpg"),#imageLiteral(resourceName: "Revival.jpg"),#imageLiteral(resourceName: "Purpose.jpg"),#imageLiteral(resourceName: "Purpose.jpg"),#imageLiteral(resourceName: "Purpose.jpg"),#imageLiteral(resourceName: "Father of Asahd.jpg"),#imageLiteral(resourceName: "Nine Track Mind.jpg"),#imageLiteral(resourceName: "thank u, next.jpg"),#imageLiteral(resourceName: "thank u, next.jpg"),#imageLiteral(resourceName: "Sweetener.jpg"),#imageLiteral(resourceName: "My Everything.jpg"),#imageLiteral(resourceName: "My Everything.jpg")]

//declares a variable that stores all of the titles of the 70s songs within the app
var seventiesSongTitles: [String] = ["Come and Get Your Love", "One More Time", "Hooked On A Feeling", "September", "Ain't No Mountain High Enough", "Southern Nights", "Sara Smile", "Brandy", "Rubber Band", "O-O-H Child", "Mr. Blue Sky", "Baby Come Back", "Escape", "Wouldn't It Be Nice", "Surrender", "Rich Girl", "Happy Together", "Return Of The Mack", "Livin' Thing", "Bohemian Rhapsody", "Another One Bites The Dust", "Rock With You", "Higher Love", "I'm Not In Love", "Go All The Way", "Cherry Bomb", "I Want You Back", "Spirit In The Sky", "Free Ride", "Play That Funky Music", "Don't Stop Til You Get Enough", "All Along The Watchtower", "Paint It Black", "Roxanne", "Highway To Hell", "The Joker", "Fly Like An Eagle", "Hollywood Nights", "Immigrant Song", "Don't Stop Me Now", "Fooled Around And Fell In Love"]

//declares a variable that stores all of the artists of the 70s songs within the app
var seventiesSongArtists: [String] = ["Redbone", "Redbone", "Blue Swede", "Earth, Wind and Fire", "Marvin Gaye", "Glen Campbell", "Hall and Oates", "Looking Glass", "The Trammps", "The Five Stairsteps", "Electric Light Orchestra", "Player", "Rupert Holmes", "The Beach Boys", "Cheap Trick", "Hall and Oates", "The Turtles", "Mark Morrison", "Electric Light Orchestra", "Queen", "Queen", "Michael Jackson", "Steve Winwood", "10cc", "Raspberries", "The Runaways", "The Jackson 5", "Norman Greenbaum", "The Edgar Winter Group", "Wild Cherry", "Michael Jackson", "Jimi Hendrix", "The Rolling Stones", "The Police", "ACDC", "Steve Miller Band", "Steve Miller Band", "Bob Seger", "Led Zeppelin", "Queen", "Elvin Bishop"]

//declares a variable that stores all of the albums of the 70s songs within the app
var seventiesSongAlbums: [String] = ["Wovoka", "Beaded Dreams Through Turquoise Eyes", "Hooked On A Feeling", "Now, Then and Forever", "United", "Southern Nights", "Daryl Hall and John Oates", "Looking Glass", "The Legendary Zing Album", "Stairsteps", "Out of the Blue", "Player", "Partners In Crime", "Pet Sounds", "Heaven Tonight", "Bigger Than Both Of Us", "Happy Together", "Return Of The Mack", "A New World Record", "A Night At The Opera", "The Game", "Off the Wall", "Back In The High Life", "The Original Soundtrack", "Raspberries", "The Runaways", "Diana Ross Presents The Jackson 5", "Spirit In The Sky", "They Only Come Out At Night", "Wild Cherry", "Off the Wall", "Electric Ladyland", "Aftermath", "Outlandos D'Amour", "Highway To Hell", "The Joker", "Fly Like An Eagle", "Stranger In Town", "Led Zeppelin III", "Jazz", "Struttin My Stuff"]

//declares a variable that stores all of the album covers of the 70s songs within the app
var seventiesSongAlbumCovers: [UIImage] = [#imageLiteral(resourceName: "Wovoka.jpg"),#imageLiteral(resourceName: "Beaded Dreams.jpg"),#imageLiteral(resourceName: "Hooked on a Feeling.jpg"),#imageLiteral(resourceName: "Now, Then and Forever.jpg"),#imageLiteral(resourceName: "United.jpg"),#imageLiteral(resourceName: "Southern Nights.jpg"),#imageLiteral(resourceName: "Daryl Hall and John Oates.jpg"),#imageLiteral(resourceName: "Looking Glass.jpg"),#imageLiteral(resourceName: "The Legendary Zing Album.jpg"),#imageLiteral(resourceName: "Stairsteps.jpg"),#imageLiteral(resourceName: "Out of the Blue.jpg"),#imageLiteral(resourceName: "Player.jpg"),#imageLiteral(resourceName: "Partners In Crime.jpg"),#imageLiteral(resourceName: "Pet Sounds.jpg"),#imageLiteral(resourceName: "Heaven Tonight.jpg"),#imageLiteral(resourceName: "Bigger Than Both Of Us.jpg"),#imageLiteral(resourceName: "Happy Together.jpg"),#imageLiteral(resourceName: "Return of the Mack.jpg"),#imageLiteral(resourceName: "A New World Record.jpg"),#imageLiteral(resourceName: "A Night At The Opera.jpg"),#imageLiteral(resourceName: "The Game.jpg"),#imageLiteral(resourceName: "Off the Wall.jpg"),#imageLiteral(resourceName: "Back In The High Life.jpg"),#imageLiteral(resourceName: "The Original Soundtrack.jpg"),#imageLiteral(resourceName: "Raspberries.jpg"),#imageLiteral(resourceName: "The Runaways.jpg"),#imageLiteral(resourceName: "Diana Ross Presents.jpg"),#imageLiteral(resourceName: "Spirit In The Sky.jpg"),#imageLiteral(resourceName: "They Only Come Out At Night.jpg"),#imageLiteral(resourceName: "Wild Cherry.jpg"),#imageLiteral(resourceName: "Off the Wall.jpg"),#imageLiteral(resourceName: "Electric Ladyland.jpg"),#imageLiteral(resourceName: "Aftermath.jpg"),#imageLiteral(resourceName: "Outlandos D'Amour.jpg"),#imageLiteral(resourceName: "Highway To Hell.jpg"),#imageLiteral(resourceName: "The Joker.jpg"),#imageLiteral(resourceName: "Fly Like An Eagle.jpg"),#imageLiteral(resourceName: "Stranger In Town.jpg"),#imageLiteral(resourceName: "Led Zeppelin III.jpg"),#imageLiteral(resourceName: "Jazz.jpg"),#imageLiteral(resourceName: "Struttin My Stuff.jpg")]
